"""fix users table

Revision ID: f4b5655c7e66
Revises: 
Create Date: 2025-08-26 15:21:33.539611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b5655c7e66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm_data',
    sa.Column('algorithm', sa.Enum('SHA256', 'SCRYPT', 'ETCHASH', 'KHEAVYHASH', 'BLAKE2S', 'BLAKE2B_SHA3', 'EAGLESONG', 'CUCKAROO', 'CUCKATOO', name='algorithm'), nullable=False),
    sa.Column('default_coin', sa.String(length=10), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('network_hashrate', sa.Float(), nullable=True),
    sa.Column('block_reward', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('algorithm')
    )
    op.create_table('asic_models',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.Enum('BITMAIN', 'WHATSMINER', 'ICERIVER', 'GOLDSHELL', 'IPOLLO', 'JASMINER', 'ELPHAPEX', 'BOMBAX', 'AVALON', 'OTHER', name='manufacturer'), nullable=False),
    sa.Column('algorithm', sa.Enum('SHA256', 'SCRYPT', 'ETCHASH', 'KHEAVYHASH', 'BLAKE2S', 'BLAKE2B_SHA3', 'EAGLESONG', 'CUCKAROO', 'CUCKATOO', name='algorithm'), nullable=False),
    sa.Column('hash_rate', sa.Float(), nullable=False),
    sa.Column('power_consumption', sa.Float(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coins',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('coin_gecko_id', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.Enum('SHA256', 'SCRYPT', 'ETCHASH', 'KHEAVYHASH', 'BLAKE2S', 'BLAKE2B_SHA3', 'EAGLESONG', 'CUCKAROO', 'CUCKATOO', name='algorithm'), nullable=False),
    sa.Column('current_price_usd', sa.Float(), nullable=True),
    sa.Column('current_price_rub', sa.Float(), nullable=True),
    sa.Column('price_change_24h', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('uname', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('USER', 'ADMIN', name='userstatus'), nullable=True),
    sa.Column('notifications', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('broadcast_messages',
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sell_requests',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['asic_models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('used_device_guide',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_device_guide')
    op.drop_table('sell_requests')
    op.drop_table('broadcast_messages')
    op.drop_table('users')
    op.drop_table('coins')
    op.drop_table('asic_models')
    op.drop_table('algorithm_data')
    # ### end Alembic commands ###
